from . import help
from . import start
from . import admin
from . import katolog
from . import shashlik
from . import napitka
from . import back
from . import ikkinchi
from . import miqdor
from . import narx
from . import savat
from . import buyurtma